services:
  - type: web
    name: wellmind-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn WellMindAi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: WellMindAi.settings
      - key: SECRET_KEY
        generateValue: true
